-- Drop Tables

DROP TABLE IF EXISTS Includes CASCADE;
DROP TABLE IF EXISTS Generates CASCADE;
DROP TABLE IF EXISTS MadeOf CASCADE;
DROP TABLE IF EXISTS Contained CASCADE;
DROP TABLE IF EXISTS Creates CASCADE;
DROP TABLE IF EXISTS GroceryList CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS MealPlan CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
